apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::857211165260:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-19P4JBV3N9STT
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:master
      rolearn: arn:aws:iam::857211165260:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-28T10:24:52Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-01-28T10:24:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2927"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: e1c907e5-0355-4eb8-b26a-f2eabb9c1983
